---
title: Votre guide et conseils pour chien
baseurl: "/"
permalink: "/:title/"
palette: orange
header:
  title: Dogeed
  logo_img: "/images/txt.PNG"
  has_nav: true
  menu:
    actions:
    - label: Sign Up
      url: "/signup"
footer:
  logo_img: "/images/txt.PNG"
  tagline: La communauté qui à du chien
  has_nav: true
  nav_title: Company
  has_social: true
  social_title: Community
  has_subscribe: true
  subscribe_title: Subscribe
  subscribe_content: Stay up to date with our latest developments.
  content: "&copy; Stackbit. All rights reserved."
  links:
  - text: "Make with \U0001F496 by Dogeed"
    url: https://dogeed.ch
    new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
- jekyll-menus
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- ssg-build.sh
- LICENSE.md
- README.md
- netlify.toml
- stackbit-build.sh
- stackbit-pull.js
collections:
  posts:
    permalink: "/posts/:title/"
